/*
 * WILLIAM YOSHIDA (wky5017)
 * CMPSC 221 - Al Verbanec - Fall 2017
 * Programming Assignment 6
 * Main GUI class
 */

import java.sql.Date;
import javax.swing.JOptionPane;
import java.util.List;

public class FlightScheduler extends javax.swing.JFrame {
    
    private Customer customer;
    private Day day;
    
    private Flight currentFlight;
    private FlightQueries flightQueries;
    
    private Bookings currentBooking;
    private BookingQueries bookingQueries;
    
    private Waiting currentWaiting;
    private WaitingQueries waitingQueries;
    
    /**
     * Creates new form FlightScheduler
     */
    public FlightScheduler() {
        initComponents();
        
        customer = new Customer();
        day = new Day();
        currentFlight = new Flight();
        flightQueries = new FlightQueries();
        currentBooking = new Bookings();
        bookingQueries = new BookingQueries();
        currentWaiting = new Waiting();
        waitingQueries = new WaitingQueries();
        dateComboBox.setModel(new javax.swing.DefaultComboBoxModel(day.getAllDays().toArray()));
        bookingDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(day.getAllDays().toArray()));
        flightComboBox.setModel(new javax.swing.DefaultComboBoxModel(flightQueries.getAllFlights().toArray()));
        bookingFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(flightQueries.getAllFlights().toArray()));
        dropFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(flightQueries.getAllFlights().toArray()));
        customerComboBox.setModel(new javax.swing.DefaultComboBoxModel(customer.getAllCustomers().toArray()));
        bookingCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(customer.getAllCustomers().toArray()));
        bookingResults.setEditable(false);
        waitingListResults.setEditable(false);
        customerResults.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        nameTextField = new javax.swing.JTextField();
        addCustomerButton = new javax.swing.JButton();
        customerNameLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bookingFlightLabel = new javax.swing.JLabel();
        bookingDateLabel = new javax.swing.JLabel();
        bookingCustomerLabel = new javax.swing.JLabel();
        bookingFlightComboBox = new javax.swing.JComboBox<>();
        bookingDateComboBox = new javax.swing.JComboBox<>();
        bookingCustomerComboBox = new javax.swing.JComboBox<>();
        bookingButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        flightLabel = new javax.swing.JLabel();
        dateComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookingResults = new javax.swing.JTextArea();
        flightStatusButton = new javax.swing.JButton();
        dateLabel = new javax.swing.JLabel();
        flightComboBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        waitingListResults = new javax.swing.JTextArea();
        waitingListButton = new javax.swing.JButton();
        customerLabel = new javax.swing.JLabel();
        customerComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        customerResults = new javax.swing.JTextArea();
        customerStatusButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        flightSeatsTextField = new javax.swing.JTextField();
        addFlightButton = new javax.swing.JButton();
        flightNameTextField = new javax.swing.JTextField();
        addDayButton = new javax.swing.JButton();
        addDayTextField = new javax.swing.JTextField();
        flightNameLabel = new javax.swing.JLabel();
        flightDayLabel = new javax.swing.JLabel();
        addDayLabel = new javax.swing.JLabel();
        dropButton = new javax.swing.JButton();
        dropFlightComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Flight Scheduler");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        addCustomerButton.setText("Add Customer");
        addCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButtonActionPerformed(evt);
            }
        });

        customerNameLabel.setText("Customer Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerNameLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(customerNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(403, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Customer", jPanel1);

        bookingFlightLabel.setText("Flight Name");

        bookingDateLabel.setText("Flight Day");

        bookingCustomerLabel.setText("Customer");

        bookingFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bookingFlightComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingFlightComboBoxActionPerformed(evt);
            }
        });

        bookingDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bookingCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bookingButton.setText("Submit Booking");
        bookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel Booking");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Select Customer and Day");

        jLabel5.setText("Select Customer, Flight, Day");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(bookingFlightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(bookingFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(bookingDateLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bookingDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(bookingCustomerLabel)
                                    .addGap(97, 97, 97)
                                    .addComponent(bookingCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookingFlightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookingFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookingDateLabel)
                    .addComponent(bookingDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookingCustomerLabel)
                    .addComponent(bookingCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Booking", jPanel3);

        flightLabel.setText("Flight Name");

        dateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bookingResults.setColumns(20);
        bookingResults.setRows(5);
        jScrollPane1.setViewportView(bookingResults);

        flightStatusButton.setText("Flight Status");
        flightStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightStatusButtonActionPerformed(evt);
            }
        });

        dateLabel.setText("Flight Day");

        flightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        flightComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightComboBoxActionPerformed(evt);
            }
        });

        waitingListResults.setColumns(20);
        waitingListResults.setRows(5);
        jScrollPane2.setViewportView(waitingListResults);

        waitingListButton.setText("Waiting List Status");
        waitingListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waitingListButtonActionPerformed(evt);
            }
        });

        customerLabel.setText("Customer");

        customerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Flight (Select Flight and Day)");

        jLabel4.setText("Waitlist (Select Day)");

        customerResults.setColumns(20);
        customerResults.setRows(5);
        jScrollPane3.setViewportView(customerResults);

        customerStatusButton.setText("Customer Status");
        customerStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerStatusButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Customer (Select Customer)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerLabel)
                            .addComponent(dateLabel)
                            .addComponent(flightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(flightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(customerStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(waitingListButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(dateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerLabel)
                    .addComponent(customerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waitingListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(57, 57, 57))
        );

        jTabbedPane1.addTab("Status", jPanel2);

        flightSeatsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightSeatsTextFieldActionPerformed(evt);
            }
        });

        addFlightButton.setText("Add Flight");
        addFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightButtonActionPerformed(evt);
            }
        });

        flightNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightNameTextFieldActionPerformed(evt);
            }
        });

        addDayButton.setText("Add Day");
        addDayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDayButtonActionPerformed(evt);
            }
        });

        addDayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDayTextFieldActionPerformed(evt);
            }
        });

        flightNameLabel.setText("Flight Name");

        flightDayLabel.setText("Flight Seats");

        addDayLabel.setText("Day");

        dropButton.setText("Drop Flight");
        dropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropButtonActionPerformed(evt);
            }
        });

        dropFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dropFlightComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropFlightComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addDayLabel)
                    .addComponent(flightNameLabel)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(flightSeatsTextField)
                                .addComponent(flightNameTextField)
                                .addComponent(addDayTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                            .addComponent(flightDayLabel)
                            .addComponent(dropFlightComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addDayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addFlightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dropButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(flightNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addFlightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(flightNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(flightDayLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(flightSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(addDayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Administrative", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingButtonActionPerformed
        // TODO add your handling code here:
        int available = flightQueries.getFlightSeats(bookingFlightComboBox.getSelectedItem().toString());
        int taken = bookingQueries.seatsBooked(bookingFlightComboBox.getSelectedItem().toString(), Date.valueOf(bookingDateComboBox.getSelectedItem().toString()));
        int result = 0;
        
        if (taken < available) {
            result = bookingQueries.addBooking(bookingCustomerComboBox.getSelectedItem().toString(),bookingFlightComboBox.getSelectedItem().toString(),Date.valueOf(bookingDateComboBox.getSelectedItem().toString()));
            if (result == 1){
                JOptionPane.showMessageDialog(this, "Customer booked!", "Customer booked", JOptionPane.PLAIN_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(this, "Customer not booked!", "Error", JOptionPane.PLAIN_MESSAGE);
            }
        }
        else {
            result = waitingQueries.addWaitList(bookingCustomerComboBox.getSelectedItem().toString(),bookingFlightComboBox.getSelectedItem().toString(),Date.valueOf(bookingDateComboBox.getSelectedItem().toString()));
            if (result == 1){
                JOptionPane.showMessageDialog(this, "Flight full! Customer waitlisted!", "Customer waitlisted", JOptionPane.PLAIN_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(this, "Flight full! Customer not waitlisted", "Error", JOptionPane.PLAIN_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_bookingButtonActionPerformed
    
    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void flightStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightStatusButtonActionPerformed
        // TODO add your handling code here:
        List< String > result = bookingQueries.statusDayFlight(flightComboBox.getSelectedItem().toString(),Date.valueOf(dateComboBox.getSelectedItem().toString()));
        
        StringBuilder sb = new StringBuilder();
        for (String s : result)
        {
            sb.append(s);
            sb.append("\n");
        }        
        
        String message = "Customers booked for flight " + flightComboBox.getSelectedItem().toString() + " on " + dateComboBox.getSelectedItem().toString();
        
        JOptionPane.showMessageDialog(this, message, "Customers booked", JOptionPane.PLAIN_MESSAGE);
        bookingResults.setText(sb.toString());
        bookingResults.setEditable(false);
    }//GEN-LAST:event_flightStatusButtonActionPerformed

    private void waitingListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waitingListButtonActionPerformed
        // TODO add your handling code here:
        List< String > result = waitingQueries.statusWaitDay(Date.valueOf(dateComboBox.getSelectedItem().toString()));
        
        StringBuilder sb = new StringBuilder();
        for (String s : result)
        {
            sb.append(s);
            sb.append("\n");
        }        
        String message = "Customers waitlisted on " + dateComboBox.getSelectedItem().toString();
        
        JOptionPane.showMessageDialog(this, message, "Customers waitlisted", JOptionPane.PLAIN_MESSAGE);
        waitingListResults.setText(sb.toString());
        waitingListResults.setEditable(false);
    }//GEN-LAST:event_waitingListButtonActionPerformed

    private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtonActionPerformed
        // TODO add your handling code here:
        int result = customer.addCustomer(nameTextField.getText());
        
        if (result == 1)
            JOptionPane.showMessageDialog(this, "Customer added!", "Customer added", JOptionPane.PLAIN_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "Customer not added!", "Error", JOptionPane.PLAIN_MESSAGE);
        
        nameTextField.setText("");
        customerComboBox.setModel(new javax.swing.DefaultComboBoxModel(customer.getAllCustomers().toArray()));
        bookingCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(customer.getAllCustomers().toArray()));
        
    }//GEN-LAST:event_addCustomerButtonActionPerformed

    private void flightComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightComboBoxActionPerformed

    private void bookingFlightComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingFlightComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingFlightComboBoxActionPerformed

    private void flightSeatsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightSeatsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightSeatsTextFieldActionPerformed

    private void addFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightButtonActionPerformed
        // TODO add your handling code here:
        int result = flightQueries.addFlight(String.valueOf(flightNameTextField.getText()), Integer.valueOf(flightSeatsTextField.getText()));
        
        if (result == 1)
            JOptionPane.showMessageDialog(this, "Flight added!", "Flight added", JOptionPane.PLAIN_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "Flight not added!", "Error", JOptionPane.PLAIN_MESSAGE);
        
        flightNameTextField.setText("");
        flightSeatsTextField.setText("");
        flightComboBox.setModel(new javax.swing.DefaultComboBoxModel(flightQueries.getAllFlights().toArray()));
        bookingFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(flightQueries.getAllFlights().toArray()));
        dropFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(flightQueries.getAllFlights().toArray()));
    }//GEN-LAST:event_addFlightButtonActionPerformed

    private void flightNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightNameTextFieldActionPerformed

    private void addDayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDayButtonActionPerformed
        // TODO add your handling code here:
        int result = day.addDay(Date.valueOf(addDayTextField.getText()));
        
        if (result == 1)
            JOptionPane.showMessageDialog(this, "Day added!", "Day added", JOptionPane.PLAIN_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "Day not added!", "Error", JOptionPane.PLAIN_MESSAGE);
        
        addDayTextField.setText("");
        bookingDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(day.getAllDays().toArray()));
        dateComboBox.setModel(new javax.swing.DefaultComboBoxModel(day.getAllDays().toArray()));
    }//GEN-LAST:event_addDayButtonActionPerformed

    private void addDayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDayTextFieldActionPerformed

    private void customerStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerStatusButtonActionPerformed
        // TODO add your handling code here:
        List< String > resultBookings = bookingQueries.statusCustomerBooking(customerComboBox.getSelectedItem().toString());
        List< String > resultWaiting = waitingQueries.statusCustomerWait(customerComboBox.getSelectedItem().toString());
        
        StringBuilder sb = new StringBuilder();
        for (String s : resultBookings)
        {
            sb.append(s);
        }        
        
        for (String s : resultWaiting)
        {
            sb.append(s);
        }         
        
        String message = "Flights booked or waitlisted for customer, " + customerComboBox.getSelectedItem().toString();
        
        JOptionPane.showMessageDialog(this, message, "Flights booked or waitlisted", JOptionPane.PLAIN_MESSAGE);
        customerResults.setText(sb.toString());
        customerResults.setEditable(false);
    }//GEN-LAST:event_customerStatusButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        int resultWait = waitingQueries.dropWaitCustomer(bookingCustomerComboBox.getSelectedItem().toString(), Date.valueOf(bookingDateComboBox.getSelectedItem().toString()));
        String flight = bookingQueries.dropBookingCustomer(bookingCustomerComboBox.getSelectedItem().toString(), Date.valueOf(bookingDateComboBox.getSelectedItem().toString()));
        String message = "Booking for customer, " + bookingCustomerComboBox.getSelectedItem().toString() +  ", canceled!";
        JOptionPane.showMessageDialog(this, message, "Booking canceled", JOptionPane.PLAIN_MESSAGE);
       
        if (flight == ""){
        }
        else {
            System.out.println("Booking removed");
            String customerName = waitingQueries.getFirstWait(flight, Date.valueOf(bookingDateComboBox.getSelectedItem().toString()));
            int resultLeaveWait = waitingQueries.dropWaitCustomer(customerName, Date.valueOf(bookingDateComboBox.getSelectedItem().toString()));
            int result = bookingQueries.addBooking(customerName, flight, Date.valueOf(bookingDateComboBox.getSelectedItem().toString()));
            if (result == 1){
                String newMessage = "Seat available! Waitlisted customer, " + customerName +  ", booked!";
                JOptionPane.showMessageDialog(this, newMessage, "Waitlisted customer booked", JOptionPane.PLAIN_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(this, "Waitlisted customer not booked!", "Error", JOptionPane.PLAIN_MESSAGE);
            }
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void dropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropButtonActionPerformed
        // TODO add your handling code here:
        List< Bookings > customersDropped = bookingQueries.droppedCustomers(dropFlightComboBox.getSelectedItem().toString());
        List< String > allFlights = flightQueries.getAllFlights();
        
        for (Bookings b: customersDropped){
            
            String rebookCustomer = b.getCustomer();
            Date rebookDate = b.getDay();
            int rebooked = 0;
            
            for (String f: allFlights){
                
                if (rebooked == 0){
                    int available = flightQueries.getFlightSeats(f);
                    int taken = bookingQueries.seatsBooked(f, rebookDate);

                    if (taken < available) {
                        int resultRebooking = bookingQueries.addBooking(rebookCustomer, f, rebookDate);
                        if (resultRebooking == 1){
                            String message = "Customer, " + rebookCustomer +  ", rebooked on flight " + f + " on " + rebookDate.toString();
                            JOptionPane.showMessageDialog(this, message, "Customer rebooked", JOptionPane.PLAIN_MESSAGE);
                            rebooked = 1;
                        }
                        else {
                            String errorMessage = "Customer, " + rebookCustomer +  ", could not be rebooked!";
                            JOptionPane.showMessageDialog(this, errorMessage, "Error", JOptionPane.PLAIN_MESSAGE);
                        } 
                    }
                }
            }
            if (rebooked == 0) {
                String failMessage = "Customer, " + rebookCustomer +  ", could not be rebooked!";
                JOptionPane.showMessageDialog(this, failMessage, "Error", JOptionPane.PLAIN_MESSAGE);
            }
        }
         
        int resultDeleteWait = waitingQueries.dropWaitFlight(dropFlightComboBox.getSelectedItem().toString());
        if (resultDeleteWait != 0){
            String newMessage = "Waitlists for flight " + dropFlightComboBox.getSelectedItem().toString() +  " were deleted.";
            JOptionPane.showMessageDialog(this, newMessage, "Waitlists deleted", JOptionPane.PLAIN_MESSAGE);
        }
        int resultDeleteFlight = flightQueries.dropFlight(dropFlightComboBox.getSelectedItem().toString());
        flightComboBox.setModel(new javax.swing.DefaultComboBoxModel(flightQueries.getAllFlights().toArray()));
        bookingFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(flightQueries.getAllFlights().toArray()));
        dropFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(flightQueries.getAllFlights().toArray()));
    }//GEN-LAST:event_dropButtonActionPerformed

    private void dropFlightComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropFlightComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropFlightComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlightScheduler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JButton addDayButton;
    private javax.swing.JLabel addDayLabel;
    private javax.swing.JTextField addDayTextField;
    private javax.swing.JButton addFlightButton;
    private javax.swing.JButton bookingButton;
    private javax.swing.JComboBox<String> bookingCustomerComboBox;
    private javax.swing.JLabel bookingCustomerLabel;
    private javax.swing.JComboBox<String> bookingDateComboBox;
    private javax.swing.JLabel bookingDateLabel;
    private javax.swing.JComboBox<String> bookingFlightComboBox;
    private javax.swing.JLabel bookingFlightLabel;
    private javax.swing.JTextArea bookingResults;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> customerComboBox;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JTextArea customerResults;
    private javax.swing.JButton customerStatusButton;
    private javax.swing.JComboBox<String> dateComboBox;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton dropButton;
    private javax.swing.JComboBox<String> dropFlightComboBox;
    private javax.swing.JComboBox<String> flightComboBox;
    private javax.swing.JLabel flightDayLabel;
    private javax.swing.JLabel flightLabel;
    private javax.swing.JLabel flightNameLabel;
    private javax.swing.JTextField flightNameTextField;
    private javax.swing.JTextField flightSeatsTextField;
    private javax.swing.JButton flightStatusButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton waitingListButton;
    private javax.swing.JTextArea waitingListResults;
    // End of variables declaration//GEN-END:variables
}
